account/urls.py
from django.urls import path
from . import views

app_name = 'account'


urlpatterns = [
    path('register',views.register,name='register'),
    path('confirm',views.confirm,name='confirm'),
    path('login', views.login, name='login'),
    path('logout',views.logout,name='logout'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('resend_sms',views.resend_sms_code,name='resend_sms_code'),
    path('forget_password',views.forget_password,name='forget_password'),
    path('reset_password',views.reset_password,name='reset_password'),
]

competition/urls.py
from django.urls import path
from . import views
app_name = 'competition'
urlpatterns = [

    # path('competitions/enable/list',views.competitions_enable_list,name='enable_list'),
    path('gallery',views.gallery_list,name='gallery_list'),
    path('competition_list',views.competition_list,name='competition_list'),
    path('ranking_list',views.ranking_list,name='ranking_list'),
    path('filter_competition_list',views.filter_competition_list,name='filter_competition_list'),
    path('filter_competition_list',views.filter_competition_list,name='filter_competition_list'),
    path('filter_competition_list',views.filter_competition_list,name='filter_competition_list'),
    path('register/register_in_competition/<str:cmpt_id>',views.register_in_competition,name='register_in_competition'),
    path('register/final_register',views.final_register,name='final_register'),
    path('register/',views.register,name='register'),
]

competition_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('account.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('competition/',include('competition.urls')),
    path('news/',include('news.urls')),
    path('',include('pages.urls')),
    path('panel/',include('panel.urls')),
    path('polls/',include('polls.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('list',views.news_list,name='news_list'),
    path('detail/<int:news_id>',views.news_detail,name='news_detail')
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('honors/list', views.honors_list, name='honors_list'),
    path('honors/<int:honors_id>',views.honors_detail,name='honors_detail'),
    path('filter_gender', views.filter_gender, name='filter_gender'),
]

panel/urls.py
from django.urls import path,include
from . import views
app_name = 'panel'
urlpatterns = [

    path('panel_profile',views.panel_profile,name='panel_profile'),
    path('panel_profile/panel_profile_edit',views.panel_profile_edit,name='panel_profile_edit'),
    path('panel_profile/panel_profile_change_pass',views.panel_profile_change_pass,name='panel_profile_change_pass'),
    path('panel_dashboard',views.panel,name='panel_dashboard'),
    path('panel_company',views.panel_company,name='panel_company'),

    #gallery
    path('panel_gallery/panel_gallery_list', views.panel_gallery_list, name='panel_gallery_list'),
    path('panel_gallery/panel_gallery_add', views.panel_gallery_add, name='panel_gallery_add'),
    path('panel_gallery/panel_gallery_enable', views.panel_gallery_enable, name='panel_gallery_enable'),
    path('panel_gallery/panel_gallery_delete', views.panel_gallery_delete, name='panel_gallery_delete'),
    path('panel_gallery/panel_gallery_edit/<int:image_id>', views.panel_gallery_edit, name='panel_gallery_edit'),

    #honors
    path('panel_honor/panel_honor_list', views.panel_honors_list, name='panel_honors_list'),
    path('panel_honor/panel_honors_add', views.panel_honors_add, name='panel_honors_add'),
    path('panel_honor/panel_honors_edit/<int:honors_id>', views.panel_honors_edit, name='panel_honors_edit'),
    path('panel_honor/panel_honors_delete', views.panel_honors_delete, name='panel_honors_delete'),
    path('panel_honor/panel_honors_enable', views.panel_honors_enable, name='panel_honors_enable'),

    #survey
    path('panel_survey/panel_survey_list', views.panel_survey_list, name='panel_survey_list'),
    path('panel_survey/panel_survey_add', views.panel_survey_add, name='panel_survey_add'),
    path('panel_survey/panel_survey_enable', views.panel_survey_enable, name='panel_survey_enable'),
    path('panel_survey/panel_survey_delete', views.panel_survey_delete, name='panel_survey_delete'),
    path('panel_survey/panel_survey_edit/<int:survey_id>', views.panel_survey_edit, name='panel_survey_edit'),
    path('panel_survey/panel_items_edit/<int:survey_id>', views.panel_items_edit, name='panel_items_edit'),

    #news urls
    path('panel_news/panel_news_add',views.panel_news_add,name='panel_news_add'),
    path('panel_news/panel_news_list',views.panel_news_list,name='panel_news_list'),
    path('panel_news/panel_news_delete',views.panel_news_delete,name='panel_news_delete'),
    path('panel_news/panel_news_edit/<int:news_id>',views.panel_news_edit,name='panel_news_edit'),
    path('panel_news/panel_news_enable', views.panel_news_enable, name='panel_news_enable'),
    path('panel_news/add_category_news', views.add_category_news, name='add_category_news'),
    path('panel_news/select_cat_news', views.select_cat_news, name='select_cat_news'),
    path('panel_news/delete_category', views.delete_category, name='delete_category'),
    path('panel_news/list_category', views.list_category, name='list_category'),
    path('panel_news/delete_cat_news', views.delete_cat_news, name='delete_cat_news'),
    path('panel_news/category_selected', views.category_selected, name='category_selected'),


    #users urls
    path('panel_users/panel_user_list', views.panel_user_list, name='panel_user_list'),
    path('panel_users/panel_user_search', views.panel_user_search, name='panel_user_search'),
    path('panel_users/panel_user_edit/<int:user_id>', views.panel_user_edit, name='panel_user_edit'),
    path('panel_users/panel_user_enable', views.panel_user_enable, name='panel_user_enable'),
    # path('delete_user/<int:user_id>', views.delete_user, name='delete_user'),

    #competition url
    path('panel_competition/panel_competition_list',views.panel_competition_list,name='panel_competition_list'),
    path('panel_competition/panel_competition_add',views.panel_competition_add,name='panel_competition_add'),
    path('panel_competition/panel_competition_edit/<int:cmp_id>',views.panel_competition_edit,name='panel_competition_edit'),
    path('panel_competition/panel_competition_enable',views.panel_competition_enable,name='panel_competition_enable'),
    path('panel_competition/panel_competition_delete',views.panel_competition_delete,name='panel_competition_delete'),
    path('panel_competition/panel_competition_user/<int:cmp_id>',views.panel_competition_user,name='panel_competition_user'),
    path('panel_competition/panel_user_in_competition_enable',views.panel_user_in_competition_enable,name='panel_user_in_competition_enable'),


    path('panel_competition/panel_user_reject',views.panel_user_reject,name='panel_user_reject'),
    path('panel_competition/update_weight',views.update_weight,name='update_weight'),
    path('panel_competition/point_save',views.point_save,name='point_save'),
    # path('panel_competition/update_age_and_weight',views.update_age_and_weight,name='update_age_and_weight'),


    # path('panel_competition/panel_user_in_competition_edit',views.panel_user_in_competition_edit,name='panel_user_in_competition_edit'),

    path('panel_competition/panel_competition_rank/<int:cmp_id>',views.panel_competition_rank,name='panel_competition_rank'),
    path('panel_competition/panel_competition_weight',views.panel_competition_weight,name='panel_competition_weight'),
    path('panel_competition/check_len_weight_table',views.check_len_weight_table,name='check_len_weight_table'),

]

templates/site_pages/partials/_footer.html
{% load static %}
<div id="Footer_resize">
    <div id="Footer">
        <div class="Footer_cat">
            <div class="footer_70">
                <div class="footer_33">
                    <a href="{% url 'pages:index' %}">صفحه اصلی</a>
                    <a>مسابقات</a>
                    <a>رتبه بندی استانی</a>
                    <a href="{% url 'pages:about' %}">درباره هیئت</a>
                    <a href="{% url 'pages:contact' %}">تماس با هیئت</a>
                </div>
                <div class="footer_33">
                    {% for cat in cat_news %}
                            <a class="footer_search" href="{% url 'news:news_list' %}?cat={{ cat.title }}"> {{ cat.title }}</a>
                        {% if forloop.counter|divisibleby:5 %}
                            </div>
                            <div class="footer_33">
                        {% endif %}

                    {% endfor %}
                    </div>

                <div class="clr"></div>


            </div>

            <div class="clr"></div>
        </div>

        <div>{{ info.address |safe }}</div>
        <div class="footer_logo">
            <img src="{% static 'images/logo.aspx.png' %}" width="150" height="150" alt="نشانن ملی ثبت">
            <img src="{% static 'images/elogo.aspx.png' %}" width="125" height="136" alt="نماد اعتماد الکترونیکی">
        </div>
    </div>
</div><!-- end Footer_resize -->

templates/site_pages/partials/_navbar.html
{% load static %}
<div id="Header_resize">
    <div id="Header">
        {% if user.is_authenticated %}
            <div id="Login_Register">
                <a title="">{{ user.first_name }} عزیز خوش آمدید | </a>
                {% if user.is_staff is True %}
                    <a href="{% url 'panel:panel_profile' %}" target="_blank" title="مشاهده پنل ادمین"><i class="fa fa-user"></i></a>
                {% else %}
                    <a href="{% url 'account:dashboard' %}" target="_blank" title="مشاهده پروفایل"><i class="fa fa-user"></i></a>
                {% endif %}

                <a class="nav-link" title="خروج از حساب کاربری" href="javascript:{document.getElementById('logout').submit()}">
                    <i class="fa fa-sign-out"></i></a>
                <form action="{% url 'account:logout' %}" id="logout" method="post">
                    {% csrf_token %}

                </form>
            </div>


        {% else %}
            <div id="Login_Register">
                <a href="{% url 'account:register' %}" target="_blank">ورود اعضا | ثبت نام</a>
            </div>
        {% endif %}

        <div id="Menu">
            <div id="navigation">
                <span class="responsive_menu_icon" onclick="open_menu(this)" data-open="0"><i class="fa fa-align-justify"></i></span>

                <ul>
                    <li class="dropnav"><a href="{% url 'pages:index' %}" class="hvr-underline">صفحه اصلی</a></li>
                    <li class="dropnav"><a href="{% url 'competition:competition_list' %}" class="hvr-underline">مسابقات</a></li>
                    <li class="dropnav"><a href="{% url 'competition:ranking_list' %}" class="hvr-underline">رنکینگ</a></li>
                    <li class="dropnav"><a href="{% url 'news:news_list' %}" class="hvr-underline">اخبار</a></li>
                    <li class="dropnav"><a href="{% url 'pages:honors_list' %}" class="hvr-underline">تالار افتخارات</a></li>
                    <li class="dropnav"><a href="{% url 'competition:gallery_list' %}" class="hvr-underline">گالری</a></li>
                    <li class="dropnav"><a href="{% url 'pages:about' %}">درباره ما</a></li>
                    <li class="dropnav"><a href="{% url 'pages:contact' %}" class="hvr-underline">تماس با ما</a></li>
                    <div class="clr"></div>
                </ul>
            </div>

            <div id="Logo">
                <a href="{% url 'pages:index' %}">
                    {% if info.logo_img != '' %}
                        <img src="{{ info.logo_img.url }}" width="150" alt="لوگوی فدراسیون جودو">
                    {% else %}
                        <img src="{% static 'images/Logo_1.jpg' %}" width="150" alt="لوگوی فدراسیون جودو">
                    {% endif %}

                </a>

            </div>
            <div class="clr"></div>
        </div><!-- End Menu -->
    </div>
</div><!-- End Header_resize -->