competition_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('account.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('competition/',include('competition.urls')),
    path('news/',include('news.urls')),
    path('',include('pages.urls')),
    path('panel/',include('panel.urls')),
    path('polls/',include('polls.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('list',views.news_list,name='news_list'),
    path('detail/<int:news_id>',views.news_detail,name='news_detail')
]

pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('contact', views.contact, name='contact'),
    path('honors/list', views.honors_list, name='honors_list'),
    path('honors/<int:honors_id>',views.honors_detail,name='honors_detail'),
    path('filter_gender', views.filter_gender, name='filter_gender'),
]

templates/site_pages/honors/honors_detail.html
{% extends 'site_pages/base.html' %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/other.css' %}">
{% endblock %}
{% block title %}|جزئیات تالار افتخارات {% endblock %}
{% block content %}
    <div id="Wrapper_resize" class="direction">
        <div id="Wrapper">
            <div class="container box_shadow">
                <div class="container_header">
                    <div class="container_title"><a href="">{{ honors_files.0.honors_id.full_name }}</a></div>
                    <div class="search_box search_news">

                    </div>
                    <div class="clr"></div>
                </div>

                <div class="News_list" style="min-height:500px">

                    {% if honors_files %}
                        {% for honors in honors_files %}
                            {% if honors.extension == '.jpg' or honors.extension == '.png' %}

                                <div class="News_item_box">
                                    <div class="News_item box-shadow">
                                        <a href="{{ honors.file.url }}" target="_blank">
                                            <div class="News_img honor_img">
                                                <img src="{{ honors.file.url }}" width="310" height="174">

                                            </div>

                                            <div class="News_content honor_content">
                                                <div class="News_content_title">{{ honors.title }}</div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% elif honors.extension == '.ogg' or honors.extension == '.mp4' %}
                                <div class="News_item_box">
                                    <div class="News_item box-shadow">
                                        <a href="{{ honors.file.url }}" target="_blank">
                                            <div class="News_img honor_img">
                                                <video width="400" controls>
                                                    <source src="{{ honors.file.url }}" type="video/mp4" width="310" height="174">
                                                    <source src="{{ honors.file.url }}" type="video/ogg" width="310" height="174">
                                                    <source src="{{ honors.file.url }}" type="video/webm" width="310" height="174">
                                                </video>

                                            </div>

                                            <div class="News_content honor_content">
                                                <div class="News_content_title">{{ honors.title }}</div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% elif  honors.extension == '.pdf' %}
                                <div class="News_item_box">
                                    <div class="News_item box-shadow">
                                        <a href="{{ honors.file.url }}" target="_blank">
                                            <div class="News_img honor_img">
                                                <img src="{% static 'images/pdf.jpg' %}" width="310" height="174">
                                            </div>

                                            <div class="News_content honor_content">
                                                <div class="News_content_title">{{ honors.title }}</div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% elif  honors.extension == '.txt' %}
                                <div class="News_item_box">
                                    <div class="News_item box-shadow">
                                        <a href="{{ honors.file.url }}" target="_blank">
                                            <div class="News_img honor_img">
                                                <img src="{% static 'images/pdf.jpg' %}" width="310" height="174">

                                            </div>

                                            <div class="News_content honor_content">
                                                <div class="News_content_title">{{ honors.title }}</div>
                                            </div>
                                        </a>
                                    </div>
                                </div>
                            {% else %}
                                <div class="News_item_box">
                                    <div class="News_item box-shadow">
                                        <a href="">
                                            <div class="News_img honor_img">
                                                <img src="" width="310" height="174">

                                            </div>

                                            <div class="News_content honor_content">
                                                <div class="News_content_title"></div>
                                            </div>
                                        </a>
                                    </div>
                                </div>

                            {% endif %}
                        {% endfor %}
                    {% endif %}







                    <div class="clr"></div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/site_pages/honors/honors_list.html
{% extends 'site_pages/base.html' %}
{% load static %}
{% block extrastyle %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/other.css' %}">
{% endblock %}
{% block title %}|لیست تالار افتخارات{% endblock %}

{% block content %}

    <div id="Wrapper_resize" class="direction">
        <div id="Wrapper">
            <div class="container box_shadow center_content">

                <div class="cat_list">
                    {% for key,value in grades.items %}
                        {% if  key|stringformat:'s' == selected_cat|stringformat:'s' %}
                            <a href="{% url 'pages:honors_list' %}?cat={{ key }}" class="cat_item actives">{{ value }}</a>
                        {% else %}
                            <a href="{% url 'pages:honors_list' %}?cat={{ key }}" class="cat_item ">{{ value }}</a>
                        {% endif %}

                    {% endfor %}

                </div>

                <div class="container_header">
                    <div class="container_title"><a href="">تالار افتخارات</a></div>
                    <div class="search_box search_news">
                    </div>
                    <div class="clr"></div>
                </div>

                <div class="News_list">
                    {% if honors_list %}
                        {% for honors in honors_list %}
                            <div class="News_item_box">
                                <div class="News_item box-shadow">
                                    <a href="{% url 'pages:honors_detail'  honors.id %}">

                                        <div class="News_img">
                                            <img src="{{ honors.image.url }}" width="310" height="174">

                                            <div class="News_img_hover">
                                                <span class="GalleryIcon" href=""></span>
                                            </div>
                                        </div>

                                        <div class="News_content honor_content">
                                            <div class="News_content_title">نام و نام خانوداگی : {{ honors.full_name }} </div>
                                            <div class="News_content_txt">
                                                <span class="honor_grade">
                                                    {% for key,value in grades.items %}
                                                        {% if key == honors.grade %}
                                                            {{ value }}
                                                        {% endif %}
                                                    {% endfor %}
                                                </span>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    {% endif %}


                    <div class="clr"></div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}