competition_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('account.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('competition/',include('competition.urls')),
    path('news/',include('news.urls')),
    path('',include('pages.urls')),
    path('panel/',include('panel.urls')),
    path('polls/',include('polls.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('list',views.news_list,name='news_list'),
    path('detail/<int:news_id>',views.news_detail,name='news_detail')
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('vote/', views.vote, name='vote'),

]

templates/site_pages/load_pages/survey_form.html
{% load mathfilters %}
{% if choices_question %}
    {% for choice in choices_question %}
        <div class="progressbar_item">
            <input id="radio_{{ forloop.counter }}" {% if user.is_authenticated %}{% if user_choice_selected.choice_id == choice.choice_id %}checked{% endif %}{% endif %} type="radio" name="Survey" onchange="Survey_result('{% url 'polls:vote' %}',{{ choice.choice_id }})">
            <label for="radio_{{ forloop.counter }}">{{ choice.choice_text }}</label>

            <div class="w3-light-grey">
                <div class="w3-container w3-blue" style="width:{{ 100|mul:choice.comment | div:comment_count  |floatformat }}%">{{ 100|mul:choice.comment | div:comment_count  |floatformat }}%</div>
            </div>
        </div>
    {% endfor %}
    <p style="color: red">{{ msg }}</p>
{% endif %}