competition_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/',include('account.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
    path('competition/',include('competition.urls')),
    path('news/',include('news.urls')),
    path('',include('pages.urls')),
    path('panel/',include('panel.urls')),
    path('polls/',include('polls.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [
    path('list',views.news_list,name='news_list'),
    path('detail/<int:news_id>',views.news_detail,name='news_detail')
]

panel/urls.py
from django.urls import path,include
from . import views
app_name = 'panel'
urlpatterns = [

    path('panel_profile',views.panel_profile,name='panel_profile'),
    path('panel_profile/panel_profile_edit',views.panel_profile_edit,name='panel_profile_edit'),
    path('panel_profile/panel_profile_change_pass',views.panel_profile_change_pass,name='panel_profile_change_pass'),
    path('panel_dashboard',views.panel,name='panel_dashboard'),
    path('panel_company',views.panel_company,name='panel_company'),

    #gallery
    path('panel_gallery/panel_gallery_list', views.panel_gallery_list, name='panel_gallery_list'),
    path('panel_gallery/panel_gallery_add', views.panel_gallery_add, name='panel_gallery_add'),
    path('panel_gallery/panel_gallery_enable', views.panel_gallery_enable, name='panel_gallery_enable'),
    path('panel_gallery/panel_gallery_delete', views.panel_gallery_delete, name='panel_gallery_delete'),
    path('panel_gallery/panel_gallery_edit/<int:image_id>', views.panel_gallery_edit, name='panel_gallery_edit'),

    #honors
    path('panel_honor/panel_honor_list', views.panel_honors_list, name='panel_honors_list'),
    path('panel_honor/panel_honors_add', views.panel_honors_add, name='panel_honors_add'),
    path('panel_honor/panel_honors_edit/<int:honors_id>', views.panel_honors_edit, name='panel_honors_edit'),
    path('panel_honor/panel_honors_delete', views.panel_honors_delete, name='panel_honors_delete'),
    path('panel_honor/panel_honors_enable', views.panel_honors_enable, name='panel_honors_enable'),

    #survey
    path('panel_survey/panel_survey_list', views.panel_survey_list, name='panel_survey_list'),
    path('panel_survey/panel_survey_add', views.panel_survey_add, name='panel_survey_add'),
    path('panel_survey/panel_survey_enable', views.panel_survey_enable, name='panel_survey_enable'),
    path('panel_survey/panel_survey_delete', views.panel_survey_delete, name='panel_survey_delete'),
    path('panel_survey/panel_survey_edit/<int:survey_id>', views.panel_survey_edit, name='panel_survey_edit'),
    path('panel_survey/panel_items_edit/<int:survey_id>', views.panel_items_edit, name='panel_items_edit'),

    #news urls
    path('panel_news/panel_news_add',views.panel_news_add,name='panel_news_add'),
    path('panel_news/panel_news_list',views.panel_news_list,name='panel_news_list'),
    path('panel_news/panel_news_delete',views.panel_news_delete,name='panel_news_delete'),
    path('panel_news/panel_news_edit/<int:news_id>',views.panel_news_edit,name='panel_news_edit'),
    path('panel_news/panel_news_enable', views.panel_news_enable, name='panel_news_enable'),
    path('panel_news/add_category_news', views.add_category_news, name='add_category_news'),
    path('panel_news/select_cat_news', views.select_cat_news, name='select_cat_news'),
    path('panel_news/delete_category', views.delete_category, name='delete_category'),
    path('panel_news/list_category', views.list_category, name='list_category'),
    path('panel_news/delete_cat_news', views.delete_cat_news, name='delete_cat_news'),
    path('panel_news/category_selected', views.category_selected, name='category_selected'),


    #users urls
    path('panel_users/panel_user_list', views.panel_user_list, name='panel_user_list'),
    path('panel_users/panel_user_search', views.panel_user_search, name='panel_user_search'),
    path('panel_users/panel_user_edit/<int:user_id>', views.panel_user_edit, name='panel_user_edit'),
    path('panel_users/panel_user_enable', views.panel_user_enable, name='panel_user_enable'),
    # path('delete_user/<int:user_id>', views.delete_user, name='delete_user'),

    #competition url
    path('panel_competition/panel_competition_list',views.panel_competition_list,name='panel_competition_list'),
    path('panel_competition/panel_competition_add',views.panel_competition_add,name='panel_competition_add'),
    path('panel_competition/panel_competition_edit/<int:cmp_id>',views.panel_competition_edit,name='panel_competition_edit'),
    path('panel_competition/panel_competition_enable',views.panel_competition_enable,name='panel_competition_enable'),
    path('panel_competition/panel_competition_delete',views.panel_competition_delete,name='panel_competition_delete'),
    path('panel_competition/panel_competition_user/<int:cmp_id>',views.panel_competition_user,name='panel_competition_user'),
    path('panel_competition/panel_user_in_competition_enable',views.panel_user_in_competition_enable,name='panel_user_in_competition_enable'),


    path('panel_competition/panel_user_reject',views.panel_user_reject,name='panel_user_reject'),
    path('panel_competition/update_weight',views.update_weight,name='update_weight'),
    path('panel_competition/point_save',views.point_save,name='point_save'),
    # path('panel_competition/update_age_and_weight',views.update_age_and_weight,name='update_age_and_weight'),


    # path('panel_competition/panel_user_in_competition_edit',views.panel_user_in_competition_edit,name='panel_user_in_competition_edit'),

    path('panel_competition/panel_competition_rank/<int:cmp_id>',views.panel_competition_rank,name='panel_competition_rank'),
    path('panel_competition/panel_competition_weight',views.panel_competition_weight,name='panel_competition_weight'),
    path('panel_competition/check_len_weight_table',views.check_len_weight_table,name='check_len_weight_table'),

]

templates/admin_panel_pages/load_page/cat_news_option.html
<option value="0">دسته مورد نظر را انتخاب نمایید</option>
{% if cats_list %}
    {% for cat in cats_list %}
        <option value="{{ cat.id }}">{{ cat.title }}</option>
    {% endfor %}
{% endif %}

templates/admin_panel_pages/load_page/honors_files.html
<div class="upload_link">
    {% if honors_files %}
        {% for file in honors_files %}
            <span class="item_upload">
                <div class="upload_btn"><a>مشاهده</a> <a>حذف</a></div>
                <i class="fa fa-file-{% if ( (".jpg" in file.file.url) or (".png" in file.file.url) )  %}
                    camera-retro
                {% elif ( (".mp4" in file.file.url) or (".ogg" in file.file.url) ) %}
                    video
                {% elif  (".pdf" in file.file.url)  %}
                    pdf
                {% endif %}"
                ></i>
                {{ file.title}}
            </span>
        {% endfor %}


    {% endif %}





</div>

{#            {% if ( (".jpg" in status.image.url) or (".png" in status.image.url) ) %}#}
{#    <img src={{status.image.url}}></img>#}
{#{% else %}#}
{#    <video src={{status.image.url}}></video>         #}
{#{% endif %}#}

templates/admin_panel_pages/load_page/load_cat_news_list.html
{% if cats_list %}
    {% for cat in cats_list %}
        <span>{{ cat.title }}<i class="fa fa-times" onclick="del_cat({{cat.id}})"  data-catid="{{ cat.id }}"></i></span>
    {% endfor %}
    <div class="clr"></div>
{% endif %}

templates/admin_panel_pages/load_page/load_cat_selected.html
{% if cats_list %}
    {% for cat in cats_list %}
        <span>{{ cat.title }}</span>
    {% endfor %}
    <div class="clr"></div>
{% endif %}

templates/admin_panel_pages/load_page/load_place.html
<input type="text" name="place" class="place_input" value="{{ user.place_id.place }}">

templates/admin_panel_pages/load_page/users_list.html
{% if users_list %}
    {% for user in users_list %}

        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.username }}</td>
            <td><p>{{ user.birth_date }}</p></td>
            <td>
                {% if genders %}
                    {% for key,value in genders.items %}
                        {% if  user.gender == key %}
                            {{ value }}
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </td>
            <td>
                {% if user.interest == 0 %}
                    جودو
                {% elif user.interest == 1 %}
                    دفاع شخصی
                {% else %}
                    جودو/دفاع شخصی
                {% endif %}

            </td>
            <td>
                <label class="switch">
                    <input onchange="item_Enable(this,'{% url 'panel:panel_user_enable' %}')"
                           type="checkbox" value="{{ user.id }}"
                            {% if user.activate_status == True %}
                           checked
                            {% else %}
                            {% endif %}
                    >

                    <span class="item_Enable"></span>
                    {% if user.activate_status == True %}
                        <span class="tooltip">فعال</span>
                    {% else %}
                        <span class="tooltip">غیر فعال</span>

                    {% endif %}
                </label>
            </td>
            <td>
                <a href="{% url 'panel:panel_user_edit' user.id %}" title="ویرایش">
                    <i class="fa fa-pen" aria-hidden="true"></i>
                </a>
            </td>
        </tr>
    {% endfor %}
{% endif %}

templates/admin_panel_pages/load_page/weight_change_period.html
{% if weights_period %}
    {% for weight in weights_period %}
        <option value="{{ weight.weight__id }}">{{ weight.weight__title }}</option>
    {% endfor %}
{% endif %}

templates/admin_panel_pages/load_page/weights_period.html
<td>

<select required  name="cat_age_input_user" class="cat_name_input">
{% if ages_list %}
    {% for age in ages_list %}
        {% for key,value in ages_period.items %}
            {% if key == age %}
                <option value="{{ key }}"
                {% if age_selected == age %}
                    selected
                {% endif %}
                >{{ value }}</option>
            {% endif %}

        {% endfor %}
    {% endfor %}
{% endif %}
</select>
</td>

<td>

    <select class="cat_age_input" name="cat_weight_input_user" required>

        {% if weights_period %}
            {% for weight in weights_period %}
                <option value="{{ weight.weight__id }}" {% if  weight.weight__id == weight_selected %}selected{% endif %}>{{ weight.weight__title }}</option>
            {% endfor %}
        {% endif %}

    </select>
</td>